yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<post_id>/edit/', views.post_edit, name='edit'),
    path('create/', views.post_create, name='create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = 'posts'

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    #import debug_toolbar
    #urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

yatube/templates/includes/author.html
<div class="card">
	<div class="card-body">
        <div class="h2">
 		{{ author.first_name }}{{ author.last_name }}
        </div>
    	<div class="h3 text-muted">
 		{{ author.username }}
        </div>
    </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="h6 text-muted">
 				Записей: {{ count }}
                </div>
            </li>
        </ul>
</div>

yatube/templates/includes/create_form.html
{% load user_filters %}
        {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}
        <form method="post"
          {% if is_edit %}
              action="{% url 'posts:edit' post.id %}"
          {% else %}
              action="{% url 'posts:create' %}"
          {% endif %}
              enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}<div class="form-group row my-3"
            {% if field.field.required %}
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}
          >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
        </div>
      </form>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/form.html
{% load static %}
<!DOCTYPE html>
<!--Используется html 5 версии-->
<html lang='ru'>
<!--Язык сайта - русский-->
{% load static %}
<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
          rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3'
          crossorigin='anonymous'>
<link rel='icon' href='{% static 'img/fav/fav.ico' %}' type='image'>
<link rel='apple-touch-icon' sizes='180x180' href='{% static 'img/fav/apple-touch-icon.png' %}'>
<link rel='icon' type='image/png' sizes='32x32' href='{% static 'img/fav/favicon-32x32.png' %}'>
<link rel='icon' type='image/png' sizes='16x16' href='{% static 'img/fav/favicon-16x16.png' %}'>
  <head>
    <meta charset='utf-8' />
    <!--Кодировка сайта-->
    <!--Сайт готов работать с мобильными устройствами-->
    <meta name='viewport' content='width=device-width, inicial-scale=1' />
    <!--Загружаем fav иконки-->
    <link rel='icon' href='img/fav/fav.ico' type='image' />
    <link rel='apple-touch-icon' sizes+'180x180'
    href='img/fav/apple-touch-icon.png'>
    <link
      rel='icon'
      typr='image/png'
      sizes='32x32'
      href='img/fav/favicon 32x32.png'
    />
    <link
      rel='icon'
      typr='image/png'
      sizes='16x16'
      href='img/fav/favicon 16x16.png'
    />
    <meta name='msapplication-TileColor' content='#000' />
    <meta name='theme-color' content='#ffffff' />
    <!--Подключаем файл со стандартными стилями бустрап-->
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
          rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3'
          crossorigin='anonymous'>
    <title>{% block title %}Последние обновления на сайте{% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                     <div class="card">
                         <div class="card-header">
                             {% block CardHeader %}{% endblock CardHeader %}
                         </div>
                        <div class="card-body">
                            {% block CardBody %}{% endblock CardBody %}
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class='navbar navbar-light' style='background-color: lightskyblue'>
      <div class='container'>
        <a class='navbar-brand' href='{% url 'posts:index' %}'>
          <img src = '{% static 'img/logo.png' %}' width='30' height='30' class='d-inline-block align-top' alt=''>
          <span style='color:red'>Ya</span>tube
        </a>
          {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
              <a class="nav-link {% if view_name  == 'posts:create' %}active{% endif %}"
                 href="{% url 'posts:create' %}">Новая запись</a>
            </li>
        <li class="nav-item">
          <a class="nav-link link-light
             {% if view_name == 'users:password_change' %}active{% endif %}"
             href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light
             {% if view_name == 'users:logout' %}active{% endif %}"
             href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          <li class="nav-item">
          <a class="nav-link link-dark
            {% if view_name  == 'posts:profile' %}active{% endif %}"
             href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
          </li>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light
             {% if view_name == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light
             {% if view_name == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>

        {% endif %}
          {% endwith %}
      </ul>
      </div>
    </nav>
  </header>

yatube/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}