yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<post_id>/edit/', views.post_edit, name='edit'),
    path('create/', views.post_create, name='create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = 'posts'

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    #import debug_toolbar
    #urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name='Название', max_length=200)
    slug = models.SlugField(verbose_name='Ссылка', unique=True)
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста', help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField('Картинка', upload_to='posts/', blank=True)

    def __str__(self):
        # выводим текст поста
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')
    active = models.BooleanField(default=True, verbose_name='Активен')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарий'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        UniqueConstraint(fields=['user', 'author'], name='unique_follower')
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Добавить картинку',
        }
        labels = {
            'text': 'Текст записи',
            'group': 'Группа',
            'image': 'Изображение'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Текст комментария.'}
        help_texts = {'text': 'Напиши сюда текст комментария.'}

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page

from .models import Group, Post, Follow
from .forms import PostForm, CommentForm

User = get_user_model()


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, settings.POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = None
    if request.user.is_authenticated:
        following = author.following.filter(user=request.user).exists()
    context = {'page_obj': page_obj, 'author': author, 'following': following}
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    posts_count = post.author.posts.count()
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'posts_count': posts_count,
        'request': request.user,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=edit_post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True, 'post': edit_post}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, settings.POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required()
def profile_unfollow(request, username):
    user_follower = get_object_or_404(
        Follow, user=request.user, author__username=username
    )
    user_follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
<div class="col-md-8 p-5">
  <div class="card">
    <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
    <div class="card-body">
        {% include 'includes/create_form.html' %}
    </div>
  </div>
</div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' with follow=True %}
{% for post in page_obj %}

    <ul class="list-group">
    <li class="list-group-item list-group-item-light">
      Автор: <a href="{% url 'posts:profile' post.author %}">
        {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      </a>
    </li>
    <li class="list-group-item list-group-item-light">
      Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
    </li>
    </ul>

<div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title">Заголовок</h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">Все записи группы "{{ post.group }}"</a>
    {% endif %}
  </div>
</div>

{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>{{ group.description|linebreaks }}</p>
{% for post in page_obj %}
<ul class="list-group">
  <li class="list-group-item list-group-item-light">
    Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %} <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
  </li>
  <li class="list-group-item list-group-item-light">
    Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
  </li>
</ul>
    <div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title">Заголовок</h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>
  </div>
</div>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' with index=True %}
<p>{{ group.description|linebreaks }}</p>
{% for post in page_obj %}
<ul>
  <li>
    Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %} <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
  </li>
  <li>
    Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
  </li>
</ul>
    <div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "900x300" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title">Заголовок</h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">Все записи группы "{{ post.group }}"</a>
    {% endif %}
  </div>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="row">
    <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
            <li class="list-group-item">
              Группа:
              {%  if post.group %}
              {{ post.group }}
              {% else %}
              ---Без группы---
              {% endif %}
              {% if post.group %}
              <a class="btn btn-primary" href="{% url 'posts:group_list' post.group.slug %}">все
                  записи группы</a>
              </li>
              {% endif %}
            <li class="list-group-item">
              Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{posts_count}}</span>
            </li>
            <li class="list-group-item">
              <a class="btn btn-primary" href="{% url 'posts:profile' post.author %}">Все посты
                  пользователя</a>
            </li>
          </ul>
    </aside>
    <article class="col-12 col-md-9">

<div class="card bg-light" style="width: 100%">
  {% thumbnail post.image "900x600" crop="center" upscale=True as im %}
  <img src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-body">
    <h4 class="card-title"></h4>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    {% if post.author == requser %}
      <a class="btn btn-primary btn-sm" href="{% url 'posts:edit' post.id %}">
        Редактировать запись
      </a>
    {% endif %}
  <p>{{ post }}</p>
        {% if user.is_authenticated and user == post.author %}
        <a class="btn btn-primary btn-sm" href="{% url 'posts:edit' post.id %}">Редактировать пост</a>
        {% endif %}
        <ul>
            <li>
            Автор: {{ post.author.get_full_name }}
            <a class="btn btn-primary btn-sm" href="{% url 'posts:profile' post.author %}">все посты
                пользователя</a>
            </li>
            <li>
            Дата публикации: <strong>{{ post.pub_date|date:"d E Y" }}</strong>
            </li>
        </ul>
  <a class="btn btn-primary btn-sm" href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  </div>
</div>
    </article>
</div>
    {% load user_filters %}
    {% if comments.count != 0 %}
    {% with comments.count as total_comments %}
    <hr>
    <figure>
        <blockquote class="blockquote">
            <div class="shadow-sm p-2 bg-white rounded">
                Комментариев {{ total_comments }}
            </div>
        </blockquote>
    </figure>
    {% endwith %}
    {% endif %}

    {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
        <div class="form-group mb-2">
        {{ form.text|addclass:'form-control' }}
        </div>
    <button type="submit" class="btn btn-primary">Отправить комментарий</button>
            </form>
                </div>
        </div>
    {% endif %}

    {% for comment in comments %}
        <div class="media mb-4">
            <div class="media-body">
                <div class="alert-primary" role="alert">
                    {{ comment.created|date:'d E Y' }}
    <a href"{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.get_full_name }} </a>:
                </div>
                <figure>
                    <blockquote class="blockquote">
                    <div class="shadow-sm p-3 bg-white">
                    {{ comment.text|linebreaks }}
                    </div>
                    </blockquote>
                </figure>
            </div>
        </div>

    {% empty %}
    <hr>
    <figure>
        <blockquote class="blockquote">
            <div class="shadow-sm p-2 bg-white rounded">
                Тут еще никто не писал. Будь первым!
            </div>
        </blockquote>
    </figure>
        {% endfor %}





{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя
    {% if author.get_full_name %}
        {{ author.get_full_name }}
    {% else %}
        {{ author }}
    {% endif %}
{% endblock %}

{% block content %}
<div class="card bg-light" style="width: 100%">
    <div clss="card-body">
        <h1 class="card-title">Все посты пользователя {% if author.get_full_name %}
            {{ author.get_full_name }}{% else %}{{ author }}{% endif %}</h1>
        <h3 class="card-text"> Всего постов: {{ page_obj.paginator.count }}</h3>
        {% if request.user != author %}
            {% if following %}
                <a
                class="btn btn-lg btn-primary btn-sm"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                Отписаться
                </a>
                {% else %}
                <a
                    class="btn btn-lg btn-primary btn-sm"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                Подписаться
                </a>
            {% endif %}
        {% endif %}
    </div>
</div>

{% for post in page_obj %}
    <ul>
        <li>
            Дата публикации: <strong>{{ post.pub_date|date:'d E Y' }}</strong>
            </li>
    </ul>
    <div class="card bg-light" style="width: 100%">
    {% thumbnail post.image "900x300" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}">
  {% endthumbnail %}
    <div class="card-body">
        <h4 class="card-title">Заголовок</h4>
        <p class="card-text">
            {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Подробная информация</a>
        {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">Все записи группы "{{ post.group }}"</a>
        {% endif %}
    </div>
</div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
<div>{% include 'posts/includes/paginator.html' %}</div>
</div>
 {% endblock %}